'\" t
.\"     Title: combinediff
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 23 Jan 2009
.\"    Manual: Man pages
.\"    Source: patchutils
.\"  Language: English
.\"
.TH "COMBINEDIFF" "1" "23 Jan 2009" "patchutils" "Man pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
combinediff \- create a cumulative unified patch from two incremental patches
.SH "SYNOPSIS"
.HP \w'\fBcombinediff\fR\ 'u
\fBcombinediff\fR [[\-p\ \fIn\fR] | [\-\-strip\-match=\fIn\fR]] [[\-U\ \fIn\fR] | [\-\-unified=\fIn\fR]] [[\-d\ \fIPAT\fR] | [\-\-drop\-context=\fIPAT\fR]] [[\-q] | [\-\-quiet]] [[\-z] | [\-\-decompress]] [[\-b] | [\-\-ignore\-space\-change]] [[\-B] | [\-\-ignore\-blank\-lines]] [[\-i] | [\-\-ignore\-case]] [[\-w] | [\-\-ignore\-all\-space]] [[\-\-interpolate] | [\-\-combine]] \fIdiff1\fR \fIdiff2\fR
.HP \w'\fBcombinediff\fR\ 'u
\fBcombinediff\fR {[\-\-help] | [\-\-version]}
.SH "DESCRIPTION"
.PP
combinediff creates a unified diff that expresses the sum of two diffs\&. The diff files must be listed in the order that they are to be applied\&. For best results, the diffs must have at least three lines of context\&.
.PP
Since
\fBcombinediff\fR
doesn\*(Aqt have the advantage of being able to look at the files that are to be modified, it has stricter requirements on the input format than
\fBpatch\fR(1)
does\&. The output of GNU diff will be okay, even with extensions, but if you intend to use a hand\-edited patch it might be wise to clean up the offsets and counts using
\fBrecountdiff\fR(1)
first\&.
.PP
Note, however, that the two patches must be in strict incremental order\&. In other words, the second patch must be relative to the state of the original set of files after the first patch was applied\&.
.PP
The diffs may be in context format\&. The output, however, will be in unified format\&.
.SH "OPTIONS"
.PP
\fB\-p\fR \fIn\fR, \fB\-\-strip\-match=\fR\fB\fIn\fR\fR
.RS 4
When comparing filenames, ignore the first
\fIn\fR
pathname components from both patches\&. (This is similar to the
\fB\-p\fR
option to GNU
\fBpatch\fR(1)\&.)
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Quieter output\&. Don\*(Aqt emit rationale lines at the beginning of each patch\&.
.RE
.PP
\fB\-U\fR \fIn\fR, \fB\-\-unified=\fR\fB\fIn\fR\fR
.RS 4
Attempt to display
\fIn\fR
lines of context (requires at least
\fIn\fR
lines of context in both input files)\&. (This is similar to the
\fB\-U\fR
option to GNU
\fBdiff\fR(1)\&.)
.RE
.PP
\fB\-d\fR \fIpattern\fR, \fB\-\-drop\-context=\fR\fB\fIPATTERN\fR\fR
.RS 4
Don\*(Aqt display any context on files that match the shell wildcard
\fIpattern\fR\&. This option can be given multiple times\&.
.sp
Note that the interpretation of the shell wildcard pattern does not count slash characters or periods as special (in other words, no flags are given to
\fBfnmatch\fR)\&. This is so that
\(lq*/basename\(rq\-type patterns can be given without limiting the number of pathname components\&.
.RE
.PP
\fB\-i\fR, \fB\-\-ignore\-case\fR
.RS 4
Consider upper\- and lower\-case to be the same\&.
.RE
.PP
\fB\-w\fR, \fB\-\-ignore\-all\-space\fR
.RS 4
Ignore whitespace changes in patches\&.
.RE
.PP
\fB\-b\fR, \fB\-\-ignore\-space\-change\fR
.RS 4
Ignore changes in the amount of whitespace\&.
.RE
.PP
\fB\-B\fR, \fB\-\-ignore\-blank\-lines\fR
.RS 4
Ignore changes whose lines are all blank\&.
.RE
.PP
\fB\-z\fR, \fB\-\-decompress\fR
.RS 4
Decompress files with extensions \&.gz and \&.bz2\&.
.RE
.PP
\fB\-\-interpolate\fR
.RS 4
Run as
\(lqinterdiff\(rq\&. See
\fBinterdiff\fR(1)
for more information about how the behaviour is altered in this mode\&.
.RE
.PP
\fB\-\-combine\fR
.RS 4
Run as
\(lqcombinediff\(rq\&. This is the default\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display a short usage message\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Display the version number of combinediff\&.
.RE
.SH "BUGS"
.PP
The
\fB\-U\fR
option is a bit erratic: it can control the amount of context displayed for files that are modified in both patches, but not for files that only appear in one patch (which appear with the same amount of context in the output as in the input)\&.
.SH "SEE ALSO"
.PP
\fBinterdiff\fR(1)
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.RS 4
Package maintainer
.RE
