'\" t
.\"     Title: dehtmldiff
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 17 January 2003
.\"    Manual: Man pages
.\"    Source: patchutils
.\"  Language: English
.\"
.TH "DEHTMLDIFF" "1" "17 January 2003" "patchutils" "Man pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dehtmldiff \- get usable diff from an HTML page
.SH "SYNOPSIS"
.HP \w'\fBdehtmldiff\fR\ 'u
\fBdehtmldiff\fR [\fIfile\fR...]
.HP \w'\fBdehtmldiff\fR\ 'u
\fBdehtmldiff\fR {[\-\-help] | [\-\-version]}
.SH "DESCRIPTION"
.PP
\fBdehtmldiff\fR
creates usable diff files from HTML pages\&. This is useful in the scenario where a patch has been posted to a mailing list viewable via a web page\&.
.PP
The corrected diff is sent to standard output\&. Note that you will probably need to use the
\fB\-l\fR
option when applying the patch, in order to ignore any whitespace differences there may be\&.
.SH "OPTIONS"
.PP
\fB\-\-help\fR
.RS 4
Display a short usage message\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Display the version number of dehtmldiff\&.
.RE
.SH "LIMITATIONS"
.PP
The way this command works is fairly primitive; it boils down to some simple text replacements, followed by an
\fBunwrapdiff\fR
pass\&. As a result, all of the limitations that apply to
\fBunwrapdiff\fR
also apply to
\fBdehtmldiff\fR\&.
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.RS 4
Package maintainer
.RE
