'\" t
.\"     Title: espdiff
.\"    Author: Mike Harris <mharris@redhat.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 5 March 2003
.\"    Manual: Man pages
.\"    Source: patchutils
.\"  Language: English
.\"
.TH "ESPDIFF" "1" "5 March 2003" "patchutils" "Man pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
espdiff \- apply the appropriate transformation to a set of patches
.SH "SYNOPSIS"
.HP \w'\fBespdiff\fR\ 'u
\fBespdiff\fR [\-\-deep\-brainwave\-mode] [\-\-recurse] [\-\-compare] [\fIfile\fR...]
.HP \w'\fBespdiff\fR\ 'u
\fBespdiff\fR {[\-\-help] | [\-\-version]}
.SH "DESCRIPTION"
.PP
\fBespdiff\fR
applies the appropriate transformation to a patch or set of patches, depending on what you intend to accomplish\&.
.PP
The input patches must be
\(lqclean\(rq: in other words they must apply without fuzz or offsets in whichever order they are meant to be applied\&. The exception is if you intend
\fBespdiff\fR
to clean them for you (good luck)\&.
.PP
You may find it useful to cross your fingers while the program performs its task, or to screw your eyes tight shut while imagining it doing the right thing\&.
.SH "OPTIONS"
.PP
\fB\-\-deep\-brainwave\-mode\fR
.RS 4
Probes your brain deeply in a manner that takes longer, but produces better extra sensory results\&.
.RE
.PP
\fB\-\-recurse\fR
.RS 4
Recurses neural pathways throughout all parts of the brain, in some cases determining code changes you might make far off in the future\&. You may feel a gentle tickling sensation when using this option\&.
.RE
.PP
\fB\-\-compare\fR
.RS 4
Allows the program to scan the current directory examining existing patches to determine areas of code you are likely to change again, and concentrating on these areas more closely\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display a short usage message\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Display the version number of espdiff\&.
.RE
.SH "LIMITATIONS"
.PP
Do not use this program while sleep\-walking, or before your first cup of coffee\&.
.PP
There are some cases in which it is not possible to determine what the intention of the user is\&. In these cases, you should construct the output you desire using an editor, and send the input files together with the desired output file to Tim Waugh
twaugh@redhat\&.com
asking for a new diff tool\&.
.SH "AUTHORS"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.RS 4
Package maintainer
.RE
.PP
\fBMike Harris\fR <\&mharris@redhat\&.com\&>
.RS 4
Conceptual designer
.RE
