'\" t
.\"     Title: fixcvsdiff
.\"    Author: Amir Karger <karger@post.harvard.edu>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 7 Dec 2001
.\"    Manual: Man pages
.\"    Source: patchutils
.\"  Language: English
.\"
.TH "FIXCVSDIFF" "1" "7 Dec 2001" "patchutils" "Man pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
fixcvsdiff \- fix problematic diff files
.SH "SYNOPSIS"
.HP \w'\fBfixcvsdiff\fR\ 'u
\fBfixcvsdiff\fR [\-p] [\-b] [\fIfile\fR...]
.SH "DESCRIPTION"
.PP
fixcvsdiff modifies diff files created from the
\fBcvs diff\fR
command, where files have been added or removed\&. CVS tends to create diff files that
\fBpatch\fR(1)
mis\-interprets\&. The diff file must retain the lines beginning with
\(lqIndex:\(rq
in order for the correction to work\&.
.SH "OPTIONS"
.PP
\fB\-b\fR
.RS 4
Keep a \&.bak backup file\&.
.RE
.PP
\fB\-p\fR
.RS 4
Print out the
\fBcvs add\fR
and
\fBcvs remove\fR
commands that must be made after applying the diff, but before running
\fBcvs commit\fR\&.
.RE
.SH "SEE ALSO"
.PP
\fBdiff\fR(1),
\fBpatch\fR(1),
\fBcvs\fR(1)
.SH "AUTHORS"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.RS 4
Package maintainer
.RE
.PP
\fBAmir Karger\fR <\&karger@post\&.harvard\&.edu\&>
.RS 4
Author of the original perl script and man page
.RE
.PP
\fBJohn Levon\fR <\&moz@compsoc\&.man\&.ac\&.uk\&>
.RS 4
Author of the original perl script and man page
.RE
