.\"     Title: interdiff
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.74.0 <http://docbook.sf.net/>
.\"      Date: 23 June 2009
.\"    Manual: Man pages
.\"    Source: patchutils
.\"  Language: English
.\"
.TH "INTERDIFF" "1" "23 June 2009" "patchutils" "Man pages"
.\" -----------------------------------------------------------------
.\" * (re)Define some macros
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" toupper - uppercase a string (locale-aware)
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de toupper
.tr aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ
\\$*
.tr aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" SH-xref - format a cross-reference to an SH section
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de SH-xref
.ie n \{\
.\}
.toupper \\$*
.el \{\
\\$*
.\}
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" SH - level-one heading that works better for non-TTY output
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de1 SH
.\" put an extra blank line of space above the head in non-TTY output
.if t \{\
.sp 1
.\}
.sp \\n[PD]u
.nr an-level 1
.set-an-margin
.nr an-prevailing-indent \\n[IN]
.fi
.in \\n[an-margin]u
.ti 0
.HTML-TAG ".NH \\n[an-level]"
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
\." make the size of the head bigger
.ps +3
.ft B
.ne (2v + 1u)
.ie n \{\
.\" if n (TTY output), use uppercase
.toupper \\$*
.\}
.el \{\
.nr an-break-flag 0
.\" if not n (not TTY), use normal case (not uppercase)
\\$1
.in \\n[an-margin]u
.ti 0
.\" if not n (not TTY), put a border/line under subheading
.sp -.6
\l'\n(.lu'
.\}
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" SS - level-two heading that works better for non-TTY output
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de1 SS
.sp \\n[PD]u
.nr an-level 1
.set-an-margin
.nr an-prevailing-indent \\n[IN]
.fi
.in \\n[IN]u
.ti \\n[SN]u
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.ps \\n[PS-SS]u
\." make the size of the head bigger
.ps +2
.ft B
.ne (2v + 1u)
.if \\n[.$] \&\\$*
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" BB/BE - put background/screen (filled box) around block of text
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de BB
.if t \{\
.sp -.5
.br
.in +2n
.ll -2n
.gcolor red
.di BX
.\}
..
.de EB
.if t \{\
.if "\\$2"adjust-for-leading-newline" \{\
.sp -1
.\}
.br
.di
.in
.ll
.gcolor
.nr BW \\n(.lu-\\n(.i
.nr BH \\n(dn+.5v
.ne \\n(BHu+.5v
.ie "\\$2"adjust-for-leading-newline" \{\
\M[\\$1]\h'1n'\v'+.5v'\D'P \\n(BWu 0 0 \\n(BHu -\\n(BWu 0 0 -\\n(BHu'\M[]
.\}
.el \{\
\M[\\$1]\h'1n'\v'-.5v'\D'P \\n(BWu 0 0 \\n(BHu -\\n(BWu 0 0 -\\n(BHu'\M[]
.\}
.in 0
.sp -.5v
.nf
.BX
.in
.sp .5v
.fi
.\}
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" BM/EM - put colored marker in margin next to block of text
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de BM
.if t \{\
.br
.ll -2n
.gcolor red
.di BX
.\}
..
.de EM
.if t \{\
.br
.di
.ll
.gcolor
.nr BH \\n(dn
.ne \\n(BHu
\M[\\$1]\D'P -.75n 0 0 \\n(BHu -(\\n[.i]u - \\n(INu - .75n) 0 0 -\\n(BHu'\M[]
.in 0
.nf
.BX
.in
.fi
.\}
..
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "Name"
interdiff \- show differences between two diff files
.SH "Synopsis"
.fam C
.HP \w'\fBinterdiff\fR\ 'u
\fBinterdiff\fR [[\-p\ \fIn\fR] | [\-\-strip\-match=\fIn\fR]] [[\-U\ \fIn\fR] | [\-\-unified=\fIn\fR]] [[\-d\ \fIPAT\fR] | [\-\-drop\-context=\fIPAT\fR]] [[\-q] | [\-\-quiet]] [[\-z] | [\-\-decompress]] [[\-b] | [\-\-ignore\-space\-change]] [[\-B] | [\-\-ignore\-blank\-lines]] [[\-i] | [\-\-ignore\-case]] [[\-w] | [\-\-ignore\-all\-space]] [[\-\-interpolate] | [\-\-combine] | [\-\-flip]] [\-\-no\-revert\-omitted] \fIdiff1\fR \fIdiff2\fR
.fam
.fam C
.HP \w'\fBinterdiff\fR\ 'u
\fBinterdiff\fR {[\-\-help] | [\-\-version]}
.fam
.SH "Description"
.PP
\fBinterdiff\fR
creates a unified format diff that expresses the difference between two diffs\&. The diffs must both be relative to the same files\&. For best results, the diffs must have at least three lines of context\&.
.PP
To reverse a patch, use
\FC/dev/null\F[]
for
\fIdiff2\fR\&.
.PP
To reduce the amount of context in a patch, use:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
interdiff \-U1 /dev/null patchfile
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.PP
Since
\fBinterdiff\fR
doesn\'t have the advantage of being able to look at the files that are to be modified, it has stricter requirements on the input format than
\fBpatch\fR(1)
does\&. The output of GNU diff will be okay, even with extensions, but if you intend to use a hand\-edited patch it might be wise to clean up the offsets and counts using
\fBrecountdiff\fR(1)
first\&.
.PP
Note, however, that the two patches must both be relative to the versions of the same original set of files\&.
.PP
The diffs may be in context format\&. The output, however, will be in unified format\&.
.SH "Options"
.PP
\fB\-h\fR
.RS 4
Ignored, for compatibility with older versions of interdiff\&. This option will go away soon\&.
.RE
.PP
\fB\-p\fR \fIn\fR, \fB\-\-strip\-match=\fR\fB\fIn\fR\fR
.RS 4
When comparing filenames, ignore the first
\fIn\fR
pathname components from both patches\&. (This is similar to the
\fB\-p\fR
option to GNU
\fBpatch\fR(1)\&.)
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Quieter output\&. Don\'t emit rationale lines at the beginning of each patch\&.
.RE
.PP
\fB\-U\fR \fIn\fR, \fB\-\-unified=\fR\fB\fIn\fR\fR
.RS 4
Attempt to display
\fIn\fR
lines of context (requires at least
\fIn\fR
lines of context in both input files)\&. (This is similar to the
\fB\-U\fR
option to GNU
\fBdiff\fR(1)\&.)
.RE
.PP
\fB\-d\fR \fIPATTERN\fR, \fB\-\-drop\-context=\fR\fB\fIPATTERN\fR\fR
.RS 4
Don\'t display any context on files that match the shell wildcard
\fIPATTERN\fR\&. This option can be given multiple times\&.
.sp
Note that the interpretation of the shell wildcard pattern does not count slash characters or periods as special (in other words, no flags are given to
\fBfnmatch\fR)\&. This is so that
\(lq*/basename\(rq\-type patterns can be given without limiting the number of pathname components\&.
.RE
.PP
\fB\-i\fR, \fB\-\-ignore\-case\fR
.RS 4
Consider upper\- and lower\-case to be the same\&.
.RE
.PP
\fB\-w\fR, \fB\-\-ignore\-all\-space\fR
.RS 4
Ignore whitespace changes in patches\&.
.RE
.PP
\fB\-b\fR, \fB\-\-ignore\-space\-change\fR
.RS 4
Ignore changes in the amount of whitespace\&.
.RE
.PP
\fB\-B\fR, \fB\-\-ignore\-blank\-lines\fR
.RS 4
Ignore changes whose lines are all blank\&.
.RE
.PP
\fB\-z\fR, \fB\-\-decompress\fR
.RS 4
Decompress files with extensions \&.gz and \&.bz2\&.
.RE
.PP
\fB\-\-interpolate\fR
.RS 4
Run as
\(lqinterdiff\(rq\&. This is the default\&.
.RE
.PP
\fB\-\-combine\fR
.RS 4
Run as
\(lqcombinediff\(rq\&. See
\fBcombinediff\fR(1)
for more information about how the behaviour is altered in this mode\&.
.RE
.PP
\fB\-\-no\-revert\-omitted\fR
.RS 4
(For interpolation mode only) When a file is changed by the first patch but not by the second, don\'t revert that change\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display a short usage message\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Display the version number of interdiff\&.
.RE
.SH "Examples"
.PP
Basic usage:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
interdiff \-z 3\&.2pre1\&.patch\&.gz 3\&.2pre2\&.patch\&.gz
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.PP
Reversing a patch:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
interdiff patch /dev/null
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.PP
Reversing part of a patch (and ignoring the rest):
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
filterdiff \-i file\&.c patchfile | \e
  interdiff /dev/stdin /dev/null
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.SH "Bugs"
.PP
There are currently no known bugs in interdiff; but there are some caveats\&. If you find a bug, please report it (along with a minimal test case) to Tim Waugh
\FCtwaugh@redhat\&.com\F[]\&.
.PP
There are some sets of patches in which there is just not enough information to produce a proper interdiff\&. In this case, the strategy employed is to revert the original patch and apply the new patch\&. This, unfortunately, means that interdiffs are not guaranteed to be reversible\&.
.SH "See also"
.PP
\fBcombinediff\fR(1)
.SH "Authors"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.RS 4
Package maintainer
.RE
.PP
\fBMichael K\&. Johnson\fR <\&johnsonm@redhat\&.com\&>
.RS 4
Original man page contributor
.RE
