'\" t
.\"     Title: recountdiff
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 5 July 2002
.\"    Manual: Man pages
.\"    Source: patchutils
.\"  Language: English
.\"
.TH "RECOUNTDIFF" "1" "5 July 2002" "patchutils" "Man pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
recountdiff \- recompute patch counts and offsets
.SH "SYNOPSIS"
.HP \w'\fBrecountdiff\fR\ 'u
\fBrecountdiff\fR [\fIfile\fR...]
.HP \w'\fBrecountdiff\fR\ 'u
\fBrecountdiff\fR {[\-\-help] | [\-\-version]}
.SH "DESCRIPTION"
.PP
\fBrecountdiff\fR
recomputes the counts and offsets in unified context diffs\&. It does this in two passes: first the counts are corrected by inspection of the actual patch lines, and then the offsets are adjusted according to the computed counts\&.
.PP
The corrected diff is sent to standard output\&.
.SH "OPTIONS"
.PP
\fB\-\-help\fR
.RS 4
Display a short usage message\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Display the version number of recountdiff\&.
.RE
.SH "LIMITATIONS"
.PP
There are some things that cannot be dealt with\&. If you have removed the first context line in a hunk, for example, there is no way for
\fBrecountdiff\fR
to know that\&. For more precise fixing up, use
\fBrediff\fR(1), which uses the original and modified diffs\&.
.SH "SEE ALSO"
.PP
\fBrediff\fR(1)
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.RS 4
Package maintainer
.RE
