'\" t
.\"     Title: splitdiff
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 25 May 2011
.\"    Manual: Man pages
.\"    Source: patchutils
.\"  Language: English
.\"
.TH "SPLITDIFF" "1" "25 May 2011" "patchutils" "Man pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
splitdiff \- separate out incremental patches
.SH "SYNOPSIS"
.HP \w'\fBsplitdiff\fR\ 'u
\fBsplitdiff\fR [\-a] [\-d] [\-p\ \fIn\fR] [\-E] [\fIfile\fR]
.HP \w'\fBsplitdiff\fR\ 'u
\fBsplitdiff\fR {[\-\-help] | [\-\-version]}
.SH "DESCRIPTION"
.PP
If you have a patch file composed of several incremental patches, you can use splitdiff to separate them out\&. You may want to do this in preparation for re\-combining them with
\fBcombinediff\fR(1)\&.
.PP
The effect of running splitdiff is to separate its input into a set of output files, with no output file patching the same file more than once\&.
.SH "OPTIONS"
.PP
\fB\-a\fR
.RS 4
Split out every single file\-level patch\&.
.RE
.PP
\fB\-d\fR
.RS 4
Create file names such as
a_b\&.c\&.patch
for a patch that modifies
a/b\&.c\&.
.RE
.PP
\fB\-p\fR \fIn\fR
.RS 4
Strip the first
\fIn\fR
components of the pathname to aid comparisons\&.
.RE
.PP
\fB\-E\fR
.RS 4
Don\*(Aqt use \&.patch filename extension when writing output files\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display a short usage message\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Display the version number of splitdiff\&.
.RE
.SH "SEE ALSO"
.PP
\fBcombinediff\fR(1),
\fBlsdiff\fR(1)
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.RS 4
Package maintainer
.RE
