'\" t
.\"     Title: unwrapdiff
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 17 January 2003
.\"    Manual: Man pages
.\"    Source: patchutils
.\"  Language: English
.\"
.TH "UNWRAPDIFF" "1" "17 January 2003" "patchutils" "Man pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
unwrapdiff \- demangle word\-wrapped patches
.SH "SYNOPSIS"
.HP \w'\fBunwrapdiff\fR\ 'u
\fBunwrapdiff\fR [\-v] [\fIfile\fR...]
.HP \w'\fBunwrapdiff\fR\ 'u
\fBunwrapdiff\fR {[\-\-help] | [\-\-version]}
.SH "DESCRIPTION"
.PP
\fBunwrapdiff\fR
demangles patches that have been word\-wrapped, in an attempt to make them useful\&.
.PP
The corrected diff is sent to standard output\&. Note that you will probably need to use the
\fB\-l\fR
option when applying the patch, in order to ignore any whitespace differences there may be\&.
.SH "OPTIONS"
.PP
\fB\-v\fR
.RS 4
Verbose operation\&. A list of lines that are modified in a way that might be wrong is sent to stderr\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display a short usage message\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Display the version number of unwrapdiff\&.
.RE
.SH "LIMITATIONS"
.PP
Some heuristics are used to decide whether use a space to recombine a wrapped line, or just join them together\&. Currently this is done by comparing with last three characters of a line with the first two characters of its continuation, and using a space if any of them are different\&.
.PP
The patch needs to have been valid before being word\-wrapped\&.
.PP
The last line of a hunk is nearly always ambiguous\&. If the next line begins
\(lq@@\(rq,
\(lqIndex:\ \&\(rq,
\(lqdiff\ \&\(rq
or
\(lq\-\-\-\ \&\(rq
then it is taken to be complete; otherwise it is unwrapped using the next line\&.
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.RS 4
Package maintainer
.RE
